<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.23" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.1.0" />
    <PackageReference Include="Testcontainers.MySql" Version="4.1.0" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.1.0" />
    <ProjectReference Include="..\..\src\EzOdata.SimpleCrud.AspNetCore\EzOdata.SimpleCrud.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\EzOdata.EntityFrameworkCore.AspNetCore\EzOdata.EntityFrameworkCore.AspNetCore.csproj" />
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
  </ItemGroup>

</Project>
