<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EzOdata.SimpleCrud.AspNetCore\EzOdata.SimpleCrud.AspNetCore.csproj" />
  </ItemGroup>

</Project>
